@startuml

left to right direction

package "Menu" <<Rectangle>> {
    class "UI" as menuUi {
        --
        play()
        checkResult()
    }
}

package "Calibration" <<Rectangle>> {
    class "Calibrater" as calibrater {
        data
        --
        calibrate()
    }

    class "UI" as calibrationUi {
        data
        --
        play()
        exit()
    }
}

package "Play" <<Rectangle>> {
    class "PlayManager" as playManager {
        game_objects
        score
    }
    
    class "PlusScoreObject" as plusScoreObject {
        position
    }
    
    class "MinusScoreObject" as minusScoreObject {
        position
    }
    
    abstract class "ScoreObject" as scoreObject {
    
    }
    
    class "Player" as player {
        calibrate_data
        pose
        position
    }
    
    class "UI" as playUi {
        score
    }
}

package "Result" <<Rectangle>> {
    class "UI" as resultUi {
        score
    }
}

package "Static" <<Rectangle>> {
    entity "ResultData" as resultData {
        result_id [PK]
        --
        score
        time_stamp
    }
    
    class "CalibrationData" as calibrationData {
        data
    }
}

' Menu

' Calibration
calibrater <-- calibrationUi
calibrationData <-- calibrater

' Play
playManager <-- scoreObject
playManager <-- playUi
playManager <-- player

calibrationData <-- player
resultData <-- playManager
scoreObject <|-- plusScoreObject
scoreObject <|-- minusScoreObject

' Result
resultData <-- resultUi

@enduml
